import StaticPage from "./StaticPage";

export default function PrivacyPolicyPage() {
  return (
    <StaticPage
      title="Privacy Policy"
      subtitle="Last updated: January 2025"
      sections={[
        { heading: "Information We Collect", body: "We collect information you provide directly (name, email, phone, payment info) and data generated by your use of Bokko (bookings, searches, preferences, device info, IP address)." },
        { heading: "How We Use Your Information", body: "• Process and confirm bookings\n• Send booking confirmations and receipts\n• Customer support and dispute resolution\n• Personalised workspace recommendations\n• Platform improvements and analytics\n• Marketing communications (opt-out available at any time)" },
        { heading: "Information Sharing", body: "We share your booking details with workspace operators only to the extent necessary to fulfil your booking. We do not sell your personal data to third parties. We may share anonymised, aggregated data for research or reporting purposes." },
        { heading: "Data Security", body: "Bokko uses industry-standard SSL/TLS encryption for all data in transit. Payment data is processed via PCI-DSS compliant payment gateways. We do not store card numbers on our servers." },
        { heading: "Cookies", body: "We use cookies to maintain your session, remember preferences and measure marketing effectiveness. You can disable cookies via your browser settings, though some features may not work correctly." },
        { heading: "Your Rights", body: "You have the right to access, correct or delete your personal data. To exercise these rights, email Hello@bokkoapp.com. We will respond within 30 days." },
        { heading: "Contact", body: "Data Controller: Grofeed Technology India Pvt Ltd (Brand: Bokko)\n\nRegistered Office:\nLightbridge, 07B-101 & 07A-127, Saki Vihar Rd,\nTunga Village, Chandivali, Powai,\nMumbai, Maharashtra 400072\n\nEmail: Hello@bokkoapp.com\nPhone: +91 83690 29490" },
      ]}
    />
  );
}
